import { Roboto } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "@flaticon/flaticon-uicons/css/all/all.css";
import "swiper/css";
import "./globals.css";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  // display: "swap",
});

export const metadata = {
  title: "Coxscab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
